[build]
builder = "NIXPACKS"
buildCommand = "cd wishlist && npm install && npx prisma generate && npx prisma migrate deploy && npm run build"

[deploy]
startCommand = "cd wishlist && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
